# Path configurations
folds_json: "five_folds.json"

# Fold settings
fold_index: 0
train_split_percentage: 0.8

# DataLoader settings
batch_sizes:
  train: 512
  validation: 8
  test: 1
normalization: 'none' #'linear', 'db', or 'none'
force_dim: 314 # None 160
shuffle:
  train: true
  validation: false
  test: false

additive_noise_std:
  train: 0.0
  validation: 0.0
  test: 0.0

num_workers:
  train: 4
  validation: 0
  test: 0

# STFT settings
stft:
  window_size: 128
  overlap: 64

# Model settings
model:
  name: "resnet50"  # resnet50 resnet18
  num_classes: 6            # Replace with your number of classes
  input_channels: 1          # Single-channel input
  learn_order_of_importance: true
  max_p: 1
  mask_distribution: 'exponential' #'exponential' 'uniform'
  exponential_distribution_alpha: 1

# Training settings
training:
  max_steps: !!float 1e5
  learning_rate: 8e-4
  weight_decay: 1e-2
  save_steps: 100
  logging_steps: 100
  evaluation_strategy: "steps"  # "steps" or "epoch"
  eval_steps: 100

# Inference settings
inference:
  noise_level: 0.0